In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train_data=pd.read_csv('/content/train_emoji.csv',header =None)
train_data.head()


0  1   2     3
0           never talk to me again  3 NaN   NaN
1  I am proud of your achievements  2 NaN   NaN
2   It is the worst day in my life  3 NaN   NaN
3                 Miss you so much  0 NaN   [0]
4                     food is life  4 NaN   NaN

In [ ]:
train_data.drop(labels = [2,3], axis = 1, inplace = True)


In [ ]:
test_data=(train_data)

In [ ]:

X_test = test_data[0].values
Y_test = test_data[1].values
test_data.head()

0  1
0           never talk to me again  3
1  I am proud of your achievements  2
2   It is the worst day in my life  3
3                 Miss you so much  0
4                     food is life  4

In [ ]:
Y_test

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [ ]:
X_test

array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life', 'I love you mum', 'Stop saying bullshit',
       'congratulations on your acceptance',
       'The assignment is too long ', 'I want to go play',
       'she did not answer my text ', 'Your stupidity has no limit',
       'how many points did he score', 'my algorithm performs poorly',
       'I got approved', 'Stop shouting at me',
       'Sounds like a fun plan ha ha', 'no one likes him',
       'the game just finished', 'I will celebrate soon',
       'So sad you are not coming', 'She is my dearest love', 'Good job',
       'It was funny lol', 'candy is life ', 'The chicago cubs won again',
       'I am hungry', 'I am so excited to see you after so long',
       'you did well on you exam', 'lets brunch some day',
       'he is so cute', 'How dare you ask that',
       'do you want to join me for dinner ', 'I said yes',
       'she is 

In [ ]:
pip install emojis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import emojis
emojis.db.get_emoji_aliases()

{':grinning:': '😀',
 ':smiley:': '😃',
 ':smile:': '😄',
 ':grin:': '😁',
 ':laughing:': '😆',
 ':satisfied:': '😆',
 ':sweat_smile:': '😅',
 ':rofl:': '🤣',
 ':joy:': '😂',
 ':slightly_smiling_face:': '🙂',
 ':upside_down_face:': '🙃',
 ':melting_face:': '\U0001fae0',
 ':wink:': '😉',
 ':blush:': '😊',
 ':innocent:': '😇',
 ':smiling_face_with_three_hearts:': '🥰',
 ':heart_eyes:': '😍',
 ':star_struck:': '🤩',
 ':kissing_heart:': '😘',
 ':kissing:': '😗',
 ':relaxed:': '☺️',
 ':kissing_closed_eyes:': '😚',
 ':kissing_smiling_eyes:': '😙',
 ':smiling_face_with_tear:': '\U0001f972',
 ':yum:': '😋',
 ':stuck_out_tongue:': '😛',
 ':stuck_out_tongue_winking_eye:': '😜',
 ':zany_face:': '🤪',
 ':stuck_out_tongue_closed_eyes:': '😝',
 ':money_mouth_face:': '🤑',
 ':hugs:': '🤗',
 ':hand_over_mouth:': '🤭',
 ':face_with_open_eyes_and_hand_over_mouth:': '\U0001fae2',
 ':face_with_peeking_eye:': '\U0001fae3',
 ':shushing_face:': '🤫',
 ':thinking:': '🤔',
 ':saluting_face:': '\U0001fae1',
 ':zipper_mouth_face:': '🤐',
 ':ra

In [ ]:
emoji_dict = {
    '0' : ':kissing_heart:',
    '1' : ':basketball:',
    '2' : ':grin:',
    '3' : ':cry:',
    '4' :  ':bowl_with_spoon:',
    '5' : ':clap:',
    '6' : ':angry:',
    '7' : ':dog:',
    '8' : ':1st_place_medal:',
     '9': ':car:',
    '10': ':scream:',
    '11': ':houses:'
}

for e in emoji_dict.values() :
   print ( emojis.encode(e),end=' ')

😘 🏀 😁 😢 🥣 👏 😠 🐶 🥇 🚗 😱 🏘️ 

In [ ]:
X_train = train_data[0].values
Y_train = train_data[1].values
X_train[:]



array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life', 'I love you mum', 'Stop saying bullshit',
       'congratulations on your acceptance',
       'The assignment is too long ', 'I want to go play',
       'she did not answer my text ', 'Your stupidity has no limit',
       'how many points did he score', 'my algorithm performs poorly',
       'I got approved', 'Stop shouting at me',
       'Sounds like a fun plan ha ha', 'no one likes him',
       'the game just finished', 'I will celebrate soon',
       'So sad you are not coming', 'She is my dearest love', 'Good job',
       'It was funny lol', 'candy is life ', 'The chicago cubs won again',
       'I am hungry', 'I am so excited to see you after so long',
       'you did well on you exam', 'lets brunch some day',
       'he is so cute', 'How dare you ask that',
       'do you want to join me for dinner ', 'I said yes',
       'she is 

In [ ]:
Y_train[:]

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [ ]:
X_train.shape , Y_train.shape

((132,), (132,))

In [ ]:
 f=open('/content/glove.6B.50d.txt',encoding='utf-8',mode='r')

 embedding_matrix={}

 for line in f:
   values = line.split()
   word=values[0]
   emb = np.asarray(values[1:])
  
   embedding_matrix[word]=emb
 f.close()

In [ ]:
def get_embedding_matrix_for_data(data):
    max_len = 20
    embedding_data = np.zeros( (len(data), max_len,50))
    for x in range(len(data)):
      word_in_sen = data[x].split()
      for y in range(len(word_in_sen)):

        if embedding_matrix.get(word_in_sen[y].lower()) is not None:
          embedding_data[x][y] = embedding_matrix[word_in_sen[y].lower()]
          
    return embedding_data




In [ ]:
X_train = get_embedding_matrix_for_data(X_train)

In [ ]:
X_train.shape

(132, 20, 50)

In [ ]:
X_train

array([[[ 9.5387e-02, -1.6865e-01, -1.1514e-01, ..., -4.2103e-01,
         -5.3817e-01,  1.3738e-01],
        [-3.4604e-02,  4.1087e-01, -9.7368e-02, ...,  5.6204e-01,
         -5.9770e-01,  9.5068e-01],
        [ 6.8047e-01, -3.9263e-02,  3.0186e-01, ..., -7.3297e-02,
         -6.4699e-02, -2.6044e-01],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[ 1.1891e-01,  1.5255e-01, -8.2073e-02, ..., -5.7512e-01,
         -2.6671e-01,  9.2121e-01],
        [ 3.4664e-01,  3.9805e-01,  4.8970e-01, ...,  8.6576e-02,
          3.4037e-01,  1.3588e+00],
        [-5.9180e-01,  2.7671e-01, -4.6971e-01, ..., -2.0055e-01,
         -2.6487e-01,  5.7981e-01],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  

In [ ]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:

import tensorflow as tf
from keras.utils.np_utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,LSTM


# build our model:

model = Sequential()
model.add(LSTM(134, input_shape = (20,50), return_sequences = True,activation="relu"))

model.add(Dropout(0.2))

model.add(LSTM(134,activation="relu"))
model.add(Dropout(0.2))


model.add(Dense(20,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(12, activation='softmax'))


model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_4 (LSTM)               (None, 20, 134)           99160     
                                                                 
 dropout_6 (Dropout)         (None, 20, 134)           0         
                                                                 
 lstm_5 (LSTM)               (None, 134)               144184    
                                                                 
 dropout_7 (Dropout)         (None, 134)               0         
                                                                 
 dense_4 (Dense)             (None, 20)                2700      
                                                                 
 dropout_8 (Dropout)         (None, 20)                0         
                                                                 
 dense_5 (Dense)             (None, 12)               

In [ ]:
Y_train = to_categorical(Y_train)
Y_train

array([[[[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[1., 0.],
         [0., 1.]],

        [[0., 1.],
         [1., 0.]]],


       [[[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[1., 0.],
         [0., 1.]],

        [[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]]],


       [[[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[1., 0.],
         [0., 1.]],

        [[0., 1.],
         [1., 0.]]],


       ...,


       [[[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[1., 0.],
         [0., 1.]],

        [[0., 1.],
         [1., 0.]]],


       [[[1., 0.],
         [0., 1.]],

        [[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[0., 1.],
         [1., 0.]],

        [[0., 1.],

In [ ]:
model.compile(optimizer ="adam", loss= keras.losses.categorical_crossentropy,metrics= ['accuracy'])

In [ ]:
his = model.fit(X_train, Y_train, validation_split = 0.1, batch_size=32, epochs = 50)


In [ ]:
model.evaluate(X_train,Y_train)[1]*100

5/5 [==============================] - 0s 14ms/step - loss: 1.0181 - accuracy: 0.8507


85.07462739944458

In [ ]:
X_test = get_embedding_matrix_for_data(X_test)
Y_test = to_categorical(Y_test)

In [ ]:
model.evaluate(X_test,Y_test)[1]*100

In [ ]:
Y_pred = np.argmax(model.predict(X_test), axis=-1)
Y_pred


In [ ]:
for t in range(len(test_data)):
   print(test_data[0].iloc[t])
   print('predictions: ', emojis.encode(emoji_dict[str(Y_pred[t])]))
   print('Actual: ',emojis.encode(emoji_dict[str(test_data[1].iloc[t])]) )

I am hungry
predictions:  🥣
Actual:  🥣
never talk to me again
predictions:  😢
Actual:  😠
I am proud of your achievements
predictions:  🐶
Actual:  👏
It is the worst day in my life
predictions:  😢
Actual:  😢
Miss you so much
predictions:  😢
Actual:  😘
food is life
predictions:  🥣
Actual:  🥣
I love you mum
predictions:  😘
Actual:  😘
Stop saying bullshit
predictions:  😢
Actual:  😠
congratulations on your acceptance
predictions:  😁
Actual:  😁
The assignment is too long 
predictions:  😢
Actual:  😢
I want to go play
predictions:  🏀
Actual:  🏀
she did not answer my text 
predictions:  😢
Actual:  😢
Your stupidity has no limit
predictions:  😢
Actual:  😢
how many points did he score
predictions:  🥇
Actual:  🥇
my algorithm performs poorly
predictions:  😢
Actual:  😢
I got approved
predictions:  😁
Actual:  😁
Stop shouting at me
predictions:  😢
Actual:  😢
Sounds like a fun plan ha ha
predictions:  😁
Actual:  😁
no one likes him
predictions:  😢
Actual:  😢
the game just finished
predictions:  🏀
Actual: 

In [ ]:
def get_embedding_matrix_for_data(data):
    max_len = 20
    embedding_data = np.zeros( (len(data), max_len, 50))
    word_in_sen = data.split()
    for x in range(1):
    
      for y in range(len(word_in_sen)):

        
        if embedding_matrix.get(word_in_sen[y].lower()) is not None:
          embedding_data[x][y] = embedding_matrix[word_in_sen[y].lower()]
          
    return embedding_data


In [ ]:
X_test=str(input("enter the string : "))
X_test = get_embedding_matrix_for_data(X_test)
X_test.shape
Y_pred = np.argmax(model.predict(X_test), axis=-1)
print('predictions: ', emojis.encode(emoji_dict[str(Y_pred[0])]))



enter the string : i like dog
predictions:  😘
